library(dplyr)
library(stringr)
install.packages("syuzhet")
library(syuzhet)
library(ggplot2)
library(viridis)
install.packages("stylo")
twitter.library(stylo)


library(devtools)
install_github("juliasilge/janeaustenr")
library(janeaustenr)

data(sensesensibility)
data(prideprejudice)
data(mansfieldpark)
data(emma)
data(northangerabbey)
data(persuasion)